# Tabuada
n = int(input('Digite um número para ver a sua tabuada: '))
print(n, 'x 1 = {}'.format(n*1))
print(n, 'x 2 = {}'.format(n*2))
print(n, 'x 3 = {}'.format(n*3))
print(n, 'x 4 = {}'.format(n*4))
print(n, 'x 5 = {}'.format(n*5))
print(n, 'x 6 = {}'.format(n*6))
print(n, 'x 7 = {}'.format(n*7))
print(n, 'x 8 = {}'.format(n*8))
print(n, 'x 9 = {}'.format(n*9))
print(n, 'x 10 = {}'.format(n*10))

#OU
print('_____________________________')
print('{} x {} = {}'.format(n, 1, n*1))
print('{} x {} = {}'.format(n, 2, n*2))
print('{} x {} = {}'.format(n, 3, n*3))
print('{} x {} = {}'.format(n, 4, n*4))
print('{} x {} = {}'.format(n, 5, n*5))
print('{} x {} = {}'.format(n, 6, n*6))
print('{} x {} = {}'.format(n, 7, n*7))
print('{} x {} = {}'.format(n, 8, n*8))
print('{} x {} = {}'.format(n, 9, n*9))
print('{} x {} = {}'.format(n, 10, n*10))